name: Milestone

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: A concrete outcome that belongs to a bigger goal

labels: ["Milestone"]

body:
  - type: textarea
    attributes:
      label: Context
      description: Any context that helps understand the rationale for this milestone
    validations:
      required: false

  - type: input
    attributes:
      label: Part of goal
      description: "Milestone is part of this goal:"
      placeholder: "put the issue number here"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why
      description: Motivation for the milestone
      value: |
        - 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Outcomes
      description: High level things that need to be achieved
      value: |
        - [ ] 
    validations:
      required: true

  - type: textarea
    attributes:
      label: What
      description: Concrete tasks needed to achieve the desired outcomes. Will become Epics.
      value: |
        - [ ] 
    validations:
      required: true
