name: Milestone

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: A concrete outcome that belongs to a bigger goal

labels: ["Milestone"]

body:
  - type: textarea
    attributes:
      label: Context
      description: Any context that helps understand the rationale for this milestone
    validations:
      required: false

  - type: textarea
    attributes:
      label: Why
      description: Motivation for the milestone
      value: |
        - Part of goal: 
        - 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Outcomes
      description: High level things that need to be achieved
      value: |
        - [ ] 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation checklist
      description: List of 
      value: |
        - [ ] How will this change impact the network of deployed nodes. Will straggler nodes
          - [ ] Immediately drop from the network / error out
          - [ ] Continue with the previous functionality but miss new features
          - [ ] cause query.neurobagel.org to be buggy / degraded unless all nodes update
        - [ ] What is the upgrade procedure for nodes?
        - [ ] How will these changes impact
          - [ ] The data model
          - [ ] The documentation
          - [ ] CLI
          - [ ] Inteface between query tool and federation API
        
    validations:
      required: false


