name: Matrix test
on: workflow_dispatch

jobs:
  get_repos:
    name: Get all repositories
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.get_repo.outputs.repositories }}
    steps:
      - name: Get current repositories
        id: get_repo
        env:
          GH_TOKEN: ${{ github.TOKEN }}
          MAX_REPO: 3
        run: |
          repo_list=$(gh repo list $GITHUB_REPOSITORY_OWNER --no-archived -L ${MAX_REPO} --json owner,name --jq '.[] | "\(.owner.login)/\(.name)"' | jq -cnR '[inputs | select(length>0)]')
          echo "repositories=${repo_list}" >> $GITHUB_OUTPUT

  sync_labels:
    name: Synchronize the label to each repository
    runs-on: ubuntu-latest
    needs: get_repos
    strategy:
      matrix: 
        repo: ${{fromJSON(needs.get_repos.outputs.repos)}}
    steps:
      - name: fail if label does not exist
        id: fail_missing
        env:
          GH_TOKEN: ${{ github.TOKEN }}
        run: |
          LABEL_NAME=$(jq -r '.label.name' "$GITHUB_EVENT_PATH")
          gh label list -R "$repo" -L 100 | grep -wq "${LABEL_NAME}"
        continue-on-error: true
        
      - name: handle create
        if: ${{ github.event.action }} == "workflow_dispatch"
        run: |
          echo Happy Stuff: ${{ matrix.repo }}
          echo ${{needs.get_repos.outputs.repos}}
          if [ "${{ steps.fail_missing.outcome }}" == "failure" ];then
            echo "Label does not exist"
          fi

      - name: handle edit
        if: ${{ github.event.action }} == "edited"
        run: |
          echo Editing: ${{ matrix.repo }}
          if [ "${{ steps.fail_missing.outcome }}" == "failure" ];then
            echo "Label does not exist"
          fi

      - name: handle delete
        if: ${{ github.event.action }} == "deleted"
        run: |
          echo Deleting: ${{ matrix.repo }}
          echo ${{needs.get_repos.outputs.repos}}
          if [ "${{ steps.fail_missing.outcome }}" == "failure" ];then
            echo "Label does not exist"
          fi
        
      
  
